In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [2]:
kf = KFold(n_splits=3, shuffle=True)

In [3]:
le = preprocessing.LabelEncoder()

In [4]:
clf = DecisionTreeClassifier(max_depth=10)

In [5]:
file = open("C:/Users/1/Desktop/checked_compounds_final.txt", "r", encoding="utf-8")
lines = file.readlines()

In [6]:
#no suffixes
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:3] + items[4:6] + [items[7]]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [7]:
for vector in vectors[:5]:
    print (vector)

['Abend', '<NN>', 'Brot', '<+NN>', 'no']
['Abend', '<NN>', 'Dämmerung', '<+NN>', 'no']
['Abend', '<NN>', 'Essen', '<+NN>', 'no']
['Abend', '<NN>', 'Licht', '<+NN>', 'no']
['Abend', '<NN>', 'Lied', '<+NN>', 'no']


In [8]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [9]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.37231463  0.01702004  0.4790844   0.02237402  0.10920692]
[ 0.38822076  0.01804784  0.42858596  0.04471428  0.12043116]
[ 0.43142339  0.01037035  0.40605862  0.02078712  0.13136052]
             precision    recall  f1-score   support

          0       0.42      0.46      0.44      1099
          1       0.43      0.51      0.47      1116
          2       0.24      0.08      0.12       478

avg / total       0.39      0.41      0.39      2693



In [10]:
#with suffixes
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:8]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [11]:
for vector in vectors[:5]:
    print (vector)

['Abend', '<NN>', 'no', 'Brot', '<+NN>', 'no', 'no']
['Abend', '<NN>', 'no', 'Dämmerung', '<+NN>', 'no', 'no']
['Abend', '<NN>', 'no', 'Essen', '<+NN>', 'no', 'no']
['Abend', '<NN>', 'no', 'Licht', '<+NN>', 'no', 'no']
['Abend', '<NN>', 'no', 'Lied', '<+NN>', 'no', 'no']


In [12]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [13]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.4784507   0.0118924   0.00679543  0.41397329  0.01901232  0.00303167
  0.0668442 ]
[ 0.3782516   0.05414304  0.00424382  0.38244322  0.02541543  0.00853833
  0.14696457]
[ 0.44683916  0.01789687  0.          0.38977264  0.03856766  0.01048998
  0.09643368]
             precision    recall  f1-score   support

          0       0.41      0.30      0.35      1099
          1       0.44      0.67      0.53      1116
          2       0.22      0.09      0.13       478

avg / total       0.39      0.42      0.38      2693

