In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [2]:
kf = KFold(n_splits=3, shuffle=True)

In [3]:
le = preprocessing.LabelEncoder()

In [4]:
clf = DecisionTreeClassifier(max_depth=10)

In [5]:
file = open("C:/Users/1/Desktop/compounds_final.txt", "r", encoding="utf-8")
lines = file.readlines()

In [6]:
#no suffixes
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:3] + items[4:6] + [items[7]]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [7]:
for vector in vectors[:5]:
    print (vector)

['Engel', '<NN>', 'Bild', '<+NN>', 's']
['Wolke', '<NN>', 'Schatten', '<+NN>', 'n']
['Sonne', '<NN>', 'Strahl', '<+NN>', 'n']
['Geist', '<NN>', 'ersehen', '<V>', 'er']
['Jugend', '<NN>', 'Zeit', '<+NN>', 'no']


In [8]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [9]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.37110507  0.027628    0.43584084  0.02357708  0.14184901]
[ 0.41050803  0.01632727  0.40148012  0.01929686  0.15238772]
[ 0.42461464  0.02294884  0.41103772  0.          0.14139879]
             precision    recall  f1-score   support

          0       0.44      0.55      0.49      1349
          1       0.40      0.41      0.41      1250
          2       0.22      0.06      0.09       540

avg / total       0.39      0.41      0.39      3139



In [10]:
#with suffixes
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:8]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [11]:
for vector in vectors[:5]:
    print (vector)

['Engel', '<NN>', 'no', 'Bild', '<+NN>', 'no', 's']
['Wolke', '<NN>', 'no', 'Schatten', '<+NN>', 'no', 'n']
['Sonne', '<NN>', 'no', 'Strahl', '<+NN>', 'no', 'n']
['Geist', '<NN>', 'no', 'ersehen', '<V>', 'er', 'er']
['Jugend', '<NN>', 'no', 'Zeit', '<+NN>', 'no', 'no']


In [12]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [13]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.40212508  0.03108308  0.          0.39549939  0.01437348  0.
  0.15691897]
[ 0.37283576  0.03524815  0.01272914  0.44107217  0.01305397  0.
  0.12506081]
[ 0.37906368  0.0141593   0.          0.47341927  0.01782016  0.00932937
  0.10620821]
             precision    recall  f1-score   support

          0       0.43      0.81      0.56      1349
          1       0.42      0.17      0.24      1250
          2       0.17      0.04      0.06       540

avg / total       0.38      0.42      0.35      3139

