In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [2]:
kf = KFold(n_splits=3, shuffle=True)

In [3]:
le = preprocessing.LabelEncoder()

In [4]:
clf = DecisionTreeClassifier(max_depth=10)

In [5]:
file = open("C:/Users/1/Desktop/compounds_final.txt", "r", encoding="utf-8")
lines = file.readlines()

In [6]:
#no suffixes
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:3] + items[4:6] + [items[7]]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [7]:
for vector in vectors[:5]:
    print (vector)

['Engel', '<NN>', 'Bild', '<+NN>', 's']
['Wolke', '<NN>', 'Schatten', '<+NN>', 'n']
['Sonne', '<NN>', 'Strahl', '<+NN>', 'n']
['Geist', '<NN>', 'ersehen', '<V>', 'er']
['Jugend', '<NN>', 'Zeit', '<+NN>', 'no']


In [8]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [9]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.39288837  0.02159632  0.46256619  0.00708276  0.11586636]
[ 0.40126792  0.01420566  0.48592428  0.01157271  0.08702943]
[ 0.37056748  0.03530457  0.39441951  0.01834806  0.18136038]
             precision    recall  f1-score   support

          0       0.42      0.55      0.48      1349
          1       0.38      0.39      0.38      1250
          2       0.17      0.03      0.05       540

avg / total       0.36      0.40      0.37      3139



In [10]:
#with suffixes
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:8]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [11]:
for vector in vectors[:5]:
    print (vector)

['Engel', '<NN>', 'no', 'Bild', '<+NN>', 'no', 's']
['Wolke', '<NN>', 'no', 'Schatten', '<+NN>', 'no', 'n']
['Sonne', '<NN>', 'no', 'Strahl', '<+NN>', 'no', 'n']
['Geist', '<NN>', 'no', 'ersehen', '<V>', 'er', 'er']
['Jugend', '<NN>', 'no', 'Zeit', '<+NN>', 'no', 'no']


In [12]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [13]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.31790392  0.01646438  0.00181214  0.48492227  0.02247378  0.00163092
  0.15479259]
[ 0.44084305  0.01482883  0.          0.39439024  0.01978325  0.01751723
  0.1126374 ]
[ 0.43429742  0.00631555  0.          0.40464848  0.02414227  0.
  0.13059628]
             precision    recall  f1-score   support

          0       0.43      0.55      0.48      1349
          1       0.41      0.40      0.40      1250
          2       0.14      0.06      0.08       540

avg / total       0.37      0.40      0.38      3139

