In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [2]:
kf = KFold(n_splits=3, shuffle=True)

In [3]:
le = preprocessing.LabelEncoder()

In [4]:
clf = DecisionTreeClassifier(max_depth=10)

In [5]:
file = open("C:/Users/1/Desktop/compounds_final.txt", "r", encoding="utf-8")
lines = file.readlines()

In [6]:
#no suffixes
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:3] + items[4:6] + [items[7]]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [7]:
for vector in vectors[:5]:
    print (vector)

['Engel', '<NN>', 'Bild', '<+NN>', 's']
['Wolke', '<NN>', 'Schatten', '<+NN>', 'n']
['Sonne', '<NN>', 'Strahl', '<+NN>', 'n']
['Geist', '<NN>', 'ersehen', '<V>', 'er']
['Jugend', '<NN>', 'Zeit', '<+NN>', 'no']


In [8]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [9]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.47407518  0.05242028  0.33529978  0.00207988  0.13612488]
[ 0.38610794  0.03922896  0.45061164  0.00237464  0.12167682]
[ 0.3501828   0.06017255  0.46267271  0.0051264   0.12184554]
             precision    recall  f1-score   support

          0       0.40      0.56      0.47      2007
          1       0.51      0.47      0.49      2593
          2       0.19      0.04      0.06       744

avg / total       0.42      0.44      0.42      5344



In [10]:
#with suffixes
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:8]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [11]:
for vector in vectors[:5]:
    print (vector)

['Engel', '<NN>', 'no', 'Bild', '<+NN>', 'no', 's']
['Wolke', '<NN>', 'no', 'Schatten', '<+NN>', 'no', 'n']
['Sonne', '<NN>', 'no', 'Strahl', '<+NN>', 'no', 'n']
['Geist', '<NN>', 'no', 'ersehen', '<V>', 'er', 'er']
['Jugend', '<NN>', 'no', 'Zeit', '<+NN>', 'no', 'no']


In [12]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [13]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.38539772  0.05565032  0.00919796  0.39707466  0.01338954  0.00312396
  0.13616585]
[ 0.41912672  0.05915429  0.01632761  0.36874816  0.00367273  0.00089081
  0.13207967]
[ 0.49410724  0.05102948  0.00721517  0.32834399  0.00494656  0.00522987
  0.1091277 ]
             precision    recall  f1-score   support

          0       0.37      0.41      0.39      2007
          1       0.48      0.52      0.50      2593
          2       0.16      0.06      0.08       744

avg / total       0.39      0.42      0.40      5344

