In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [2]:
kf = KFold(n_splits=3, shuffle=True)

In [3]:
le = preprocessing.LabelEncoder()

In [4]:
clf = DecisionTreeClassifier(max_depth=10)

In [5]:
file = open("C:/Users/1/Desktop/compounds_final.txt", "r", encoding="utf-8")
lines = file.readlines()

In [6]:
#no suffixes
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:3] + [items[4]] + [items[7]]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [7]:
print (vectors[:3])

[['Engel', '<NN>', 'Bild', 's'], ['Wolke', '<NN>', 'Schatten', 'n'], ['Sonne', '<NN>', 'Strahl', 'no']]


In [8]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [9]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.51375978  0.05228116  0.33492937  0.09902969]
[ 0.4343188  0.0468084  0.4084779  0.1103949]
[ 0.38939253  0.0583827   0.4309778   0.12124698]
             precision    recall  f1-score   support

          0       0.39      0.57      0.46      2007
          1       0.51      0.44      0.48      2593
          2       0.18      0.05      0.07       744

avg / total       0.42      0.43      0.42      5344



In [10]:
#with suffixes
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:5] + items[6:8]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [11]:
print (vectors[:3])

[['Engel', '<NN>', 'no', 'Bild', 'no', 's'], ['Wolke', '<NN>', 'no', 'Schatten', 'no', 'n'], ['Sonne', '<NN>', 'no', 'Strahl', 'no', 'no']]


In [12]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [13]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.34151541  0.0579048   0.0063466   0.46573474  0.00365335  0.1248451 ]
[ 0.35895254  0.05440385  0.01506957  0.47198152  0.00916453  0.09042798]
[ 0.4196272   0.04786189  0.0185041   0.37937054  0.00755358  0.12708269]
             precision    recall  f1-score   support

          0       0.39      0.46      0.42      2007
          1       0.50      0.52      0.51      2593
          2       0.21      0.06      0.09       744

avg / total       0.42      0.44      0.42      5344

