In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [2]:
kf = KFold(n_splits=3, shuffle=True)

In [3]:
le = preprocessing.LabelEncoder()

In [4]:
clf = DecisionTreeClassifier(max_depth=10)

In [5]:
file = open("C:/Users/1/Desktop/compounds_final.txt", "r", encoding="utf-8")
lines = file.readlines()

In [6]:
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:5] + items[6:8]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [7]:
print (vectors[:3])

[['Engel', '<NN>', 'no', 'Bild', 'no', 's'], ['Wolke', '<NN>', 'no', 'Schatten', 'no', 'n'], ['Sonne', '<NN>', 'no', 'Strahl', 'no', 'no']]


In [8]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [9]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.4094146   0.05825927  0.00138731  0.43984414  0.00057926  0.09051541]
[ 0.44088043  0.05413955  0.01696196  0.358506    0.01503966  0.11447239]
[ 0.39441438  0.04339542  0.00914134  0.43815556  0.00483513  0.11005818]
             precision    recall  f1-score   support

          0       0.39      0.47      0.43      2007
          1       0.50      0.53      0.51      2593
          2       0.20      0.06      0.09       744

avg / total       0.42      0.44      0.42      5344



In [10]:
vectors = []
types = []

for line in lines:
    arr = []
    line = line.strip("\n")
    items = line.split("/")
    items_new = items[1:3] + [items[4]] + [items[7]]
    for item in items_new:
        arr.append(item)
    types.append(items[-1])
    vectors.append(arr)

In [11]:
print (vectors[:3])

[['Engel', '<NN>', 'Bild', 's'], ['Wolke', '<NN>', 'Schatten', 'n'], ['Sonne', '<NN>', 'Strahl', 'no']]


In [12]:
X = np.array(vectors)
y = np.array(types)
kf.get_n_splits(X)

3

In [13]:
all_predicts = []
tests = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_df = pd.DataFrame(X_train)
    y_train_df = pd.DataFrame(y_train)
    X_test_df = pd.DataFrame(X_test)
    y_test_df = pd.DataFrame(y_test)
    
    X_train_df_DT = X_train_df.apply(le.fit_transform)
    y_train_df_DT = y_train_df.apply(le.fit_transform)  
    X_test_df_DT = X_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df.apply(le.fit_transform)
    y_test_df_DT = y_test_df_DT[0].values.tolist()
    
    clf = clf.fit(X_train_df_DT, y_train_df_DT)
    importances = clf.feature_importances_
    print (importances)
    
    predictions = clf.predict(X_test_df_DT)
    all_predicts.extend(predictions)
    tests.extend(y_test_df_DT)
    
print(classification_report(tests, all_predicts))

[ 0.48739378  0.04944742  0.34265402  0.12050478]
[ 0.44423949  0.06498001  0.39654963  0.09423087]
[ 0.49536968  0.04570119  0.36210274  0.09682639]
             precision    recall  f1-score   support

          0       0.38      0.45      0.41      2007
          1       0.49      0.52      0.50      2593
          2       0.19      0.04      0.06       744

avg / total       0.40      0.43      0.41      5344

